# -*- coding: utf-8 -*-
"""intelligent resume analyser.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZvG0uTzBJZMtGmhVQDFuhvcYQy77AoH4
"""

def clean_text(text):
    cleaned = ""
    for ch in text:
        if ch.isalnum() or ch.isspace():
            cleaned += ch.lower()
    return cleaned

def extract_keywords(text):
    words = clean_text(text).split()
    return list(set(words))

def calculate_match_score(resume_keywords, jd_keywords):
    match_count = 0
    for word in jd_keywords:
        if word in resume_keywords:
            match_count += 1
    if len(jd_keywords) == 0:
        return 0
    return (match_count / len(jd_keywords)) * 100

def analyze_resumes(job_description, resumes):
    jd_keywords = extract_keywords(job_description)
    results = []

    for name, resume_text in resumes.items():
        resume_keywords = extract_keywords(resume_text)
        score = calculate_match_score(resume_keywords, jd_keywords)
        results.append((name, round(score, 2)))

    return sorted(results, key=lambda x: x[1], reverse=True)

print("--- Intelligent Resume Analyzer ---")
job_description = input("Enter Job Description:\n")

num_resumes = int(input("\nEnter no.of.resumes to analyze: "))
resumes = {}

for i in range(num_resumes):
    name = input(f"\nEnter candidate {i+1} name: ")
    resume_text = input(f"Enter {name}'s resume text:\n")
    resumes[name] = resume_text

results = analyze_resumes(job_description, resumes)

print("\n  Resume Match Results   ")
for name, score in results:
    print(f"{name}: {score}% match")

if results:
    best_candidate = results[0][0]
    print(f"\nBest match: {best_candidate}")
else:
    print("\nNo resumes provided.")